# Generated by Django 3.1.3 on 2021-02-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('descipcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('porcentaje', models.FloatField(verbose_name='Porcentaje')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('nombre', models.CharField(max_length=50, verbose_name='Edificio')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Expensas',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('nombre', models.CharField(default='Expensa', max_length=50, verbose_name='Nombre')),
                ('expensas_puras', models.FloatField(blank=True, null=True, verbose_name='Expensas Puras')),
                ('intereses_mora', models.FloatField(blank=True, null=True, verbose_name='Intereses por Mora')),
                ('materiales_limpieza', models.FloatField(blank=True, null=True, verbose_name='materiales de limpieza')),
                ('servicios_luz', models.FloatField(blank=True, null=True, verbose_name='servicios electricidad')),
                ('sueldo_administrador', models.FloatField(blank=True, null=True, verbose_name='Sueldo Administrador')),
                ('ascensores', models.FloatField(blank=True, null=True, verbose_name='Gasto Ascensores')),
                ('aportes_encargado_limpieza', models.FloatField(blank=True, null=True, verbose_name='Aportes Encargado Limpieza')),
                ('sueldo_encargado_limpieza', models.FloatField(blank=True, null=True, verbose_name='Sueldo Encargado Limpieza')),
                ('seguro_edificio', models.FloatField(blank=True, null=True, verbose_name='Seguro Edificio')),
                ('sueldo_anual_complementario', models.FloatField(blank=True, null=True, verbose_name='Sueldo Anual Complementario')),
                ('total_gastos', models.FloatField(verbose_name='Total')),
                ('departamento_expensa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expensas.departamento', verbose_name='Departamento')),
                ('edificio_expensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expensas.edificio', verbose_name='Edificio')),
            ],
            options={
                'verbose_name': 'Expensas',
                'verbose_name_plural': 'Expensas',
            },
            bases=('base.basemodel',),
        ),
    ]
