# Generated by Django 3.1.3 on 2021-02-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(verbose_name='Estado')),
                ('created_date', models.DateField(auto_now=True, verbose_name='fecha creacion')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='fecha modificacion')),
            ],
            options={
                'verbose_name': 'Modelo Base',
            },
        ),
    ]
